/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import application.Main;
import entities.Factura;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Nerea
 */
public class PanelEditar1 extends javax.swing.JPanel {

    private JFrame ventana;
    
    private Factura facturaSeleccionada;
    /**
     * Creates new form PanelEditar1
     */
    public PanelEditar1(Factura facturaSeleccionada) {
        this.facturaSeleccionada = facturaSeleccionada;
        initComponents();
        jTextField3.setText(new SimpleDateFormat("dd/MM/yyyy").format(this.facturaSeleccionada.getFechaEmision()));
        jTextField2.setText(this.facturaSeleccionada.getDescripcion());
        jTextField1.setText(String.valueOf(this.facturaSeleccionada.getTotalImporte()));
        this.ventana = PanelPrincipal.crearVentana("Editar factura", this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(221, 249, 221));
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yrsa SemiBold", 3, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(26, 148, 37));
        jLabel1.setText("Editar factura");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 39, 518, 87));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-flecha-adelante-100.png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Laksaman", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Fecha");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setFont(new java.awt.Font("Laksaman", 0, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(102, 102, 102));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setName("fecha"); // NOI18N
        jTextField3.setSelectionColor(new java.awt.Color(0, 153, 0));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 219, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-flecha-adelante-100.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        jLabel2.setFont(new java.awt.Font("Laksaman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Descripción");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Laksaman", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(102, 102, 102));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField2.setName("descripcion"); // NOI18N
        jTextField2.setSelectionColor(new java.awt.Color(0, 153, 0));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 541, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-flecha-adelante-100.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, -1, -1));

        jLabel5.setFont(new java.awt.Font("Laksaman", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Importe total");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, -1, -1));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Laksaman", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 102, 102));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setName("importe"); // NOI18N
        jTextField1.setSelectionColor(new java.awt.Color(0, 153, 0));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, 137, 60));

        jLabel7.setFont(new java.awt.Font("Laksaman", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-factura-100.png"))); // NOI18N
        jLabel7.setText("Confirmar");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 550, -1, -1));

        jLabel3.setFont(new java.awt.Font("Laksaman", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-cancelar-85.png"))); // NOI18N
        jLabel3.setText("Limpiar");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 560, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        try {
            Main.facturaJPA.edit(new Factura(facturaSeleccionada.getCodigo(), new SimpleDateFormat("dd/MM/yyyy").parse(jTextField3.getText()),
                    jTextField2.getText(), Double.parseDouble(jTextField1.getText())));
            PanelPrincipal.crearVentana("Factura editada con éxito.", new PanelEditarOK());
            PanelPrincipal.panelEditar.actualizarTabla();
            this.ventana.dispose();
        } catch (Exception ex) {
            PanelPrincipal.crearVentana("¡ERROR!", new PanelEditarNO());
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        jTextField3.setText("");
        jTextField2.setText("");
        jTextField1.setText("");
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
