/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import application.Main;
import entities.Factura;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Nerea
 */
public class PanelBuscar extends javax.swing.JPanel {

    private JFrame ventana;
    
    /**
     * Creates new form PanelEditar1
     */
    public PanelBuscar() {
        initComponents();
        this.ventana = PanelPrincipal.crearVentana("Buscar factura", this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(221, 249, 221));
        setMaximumSize(new java.awt.Dimension(593, 160));
        setMinimumSize(new java.awt.Dimension(593, 160));
        setPreferredSize(new java.awt.Dimension(593, 160));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yrsa SemiBold", 3, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(26, 148, 37));
        jLabel1.setText("Buscar factura");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 518, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-flecha-adelante-100.png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Laksaman", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Código");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setFont(new java.awt.Font("Laksaman", 0, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(102, 102, 102));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setName("fecha"); // NOI18N
        jTextField3.setSelectionColor(new java.awt.Color(0, 153, 0));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 160, 60));

        jLabel7.setFont(new java.awt.Font("Laksaman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-lupa-48.png"))); // NOI18N
        jLabel7.setText("Buscar");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        try {
            Factura facturaEncontrada = Main.facturaJPA.findFactura(Integer.parseInt(jTextField3.getText()));
            new PanelEncontrada(facturaEncontrada);
            this.ventana.dispose();
        } catch (Exception ex) {
            PanelPrincipal.crearVentana("¡Oh no!", new PanelNoEncontrada());
        }
    }//GEN-LAST:event_jLabel7MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
